### PR TITLE
試下交卷

### PR DESCRIPTION
**Pull request by cyljacky**
好似用 PR 方便D.. 

做左幾樣野： 
- 補左 .dockerignore 拎走同 prod env 無關既 file（node_module 唔應該再 COPY 入個 image）
- 用 npm ci ，可以少D gen package-lock.json 既步驟又可以 lock package version
- 無咩特別原因既話用 alpine version 既 image 個 size 會細 D。（當然，python另計，請參閱 https://pythonspeed.com/articles/alpine-docker-python/ ）
- ~~可以用 next export 去拎個website static~~
- ~~可以用 multi-stage 去再整細D image size~~

2020-06-26 update:
- next export 同埋 multi-stage 拎走，因為有 server rendering 既必要
- 加 .gitignore 去 .dockerignore
- 拎走埋 yarn.lock 因為無用到
- 補番 python 唔好用 alpine 既原因

2020-06-27 update:
- static asset in independent layer cache

### CODE REVIEW

**Comment by gaplo917** [comment]
@cyljacky 好似誤解咗 NextJs,  通常唔係要黎做 Static site generation, 而係做 Universal Application (Server side rendering + client side rendering)

**Comment by gaplo917** [comment]
@cyljacky 

Imagine if you have many image/video assets(50MB+?), 1 line source code change will invalidate the docker layer cache and copy all assets and source code again.

**Comment by cyljacky** [comment]
I don't have much idea on it...
only i can think of is to separate layer to cache public folder, but actually not sure if `public/` and `page/` is all needed for nextjs

**Comment by gaplo917** [comment]
@cyljacky Solution is released, Check it out

**Pull request closed without merging**
